# Generated by Django 3.1.1 on 2020-10-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='ebb334e86e2d43d0bfa43631e396ecde', editable=False, max_length=32, unique=True),
        ),
    ]
