# Generated by Django 3.1.2 on 2020-10-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201002_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='bdda5e866abe426b915ed724abc78d59', editable=False, max_length=32, unique=True),
        ),
    ]
