# Generated by Django 3.1.1 on 2020-10-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201002_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='8d646ed20f2c4620baf5c5c1f3638cfa', editable=False, max_length=32, unique=True),
        ),
    ]
