# Generated by Django 3.1.2 on 2020-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201007_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='95580658bdae4b15a74d6a8b7befa973', editable=False, max_length=32, unique=True),
        ),
    ]
