# Generated by Django 3.1.2 on 2020-10-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201007_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='c1db039738d844f0b239bd552f3d0579', editable=False, max_length=32, unique=True),
        ),
    ]
