# Generated by Django 3.1.2 on 2020-10-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201007_0208'),
        ('accounts', '0003_auto_20201004_0053'),
    ]

    operations = [
    ]
