# Generated by Django 3.1.2 on 2020-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20201007_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='5takzciYSZy4DaO2h5hutA', editable=False, max_length=32, unique=True),
        ),
    ]
