# Generated by Django 3.1.2 on 2020-10-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(default='45bb9e7e39f4441187cf6acd724ef6a3', editable=False, max_length=32, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('answer', models.CharField(editable=False, max_length=200)),
                ('answer_details', models.TextField(blank=True, editable=False, max_length=500)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
