# Generated by Django 3.1.2 on 2020-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default='67c30fcfc9594f708ce301d88abe5515', editable=False, max_length=32, unique=True),
        ),
    ]
