# Generated by Django 3.1.2 on 2020-10-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20201007_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default='6d469a3ff4d54465bfe26c80210e116a', editable=False, max_length=32, unique=True),
        ),
    ]
