# Generated by Django 3.1.2 on 2020-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20201007_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.CharField(default='Enc5lVzbQ7mh7MGa9AF1vg', editable=False, max_length=32, unique=True),
        ),
    ]
