# Generated by Django 3.1.2 on 2020-10-07 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default='85ac6a9bd9a5414bac7299e55ed74ca4', editable=False, max_length=32, unique=True)),
                ('question_title', models.CharField(editable=False, max_length=100)),
                ('question_details', models.TextField(blank=True, editable=False, max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_answered', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
