# Generated by Django 3.1.2 on 2020-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='cc5d1b4e1b5b45bfa4c745dcf2f1c32d', editable=False, max_length=32, unique=True),
        ),
    ]
