# Generated by Django 3.1.2 on 2020-10-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201007_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='0676586eab084b1099508bcc2b521c4f', editable=False, max_length=32, unique=True),
        ),
    ]
