# Generated by Django 3.1.2 on 2020-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20201007_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='zr0j9fEEQIGxOSLGT989Pw', editable=False, max_length=32, unique=True),
        ),
    ]
