# Generated by Django 3.1.2 on 2020-10-24 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(default='9xcpZ-5pSB6xpK3Q2opYoA', editable=False, max_length=32, unique=True)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='')),
                ('question_limit', models.IntegerField(default=50)),
                ('no_questions_asked', models.IntegerField(default=0)),
                ('no_questions_answered', models.IntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
